services:
  stt-server:
    build: .
    ports:
      - "7920:7920"
    volumes:
      - ./uploads:/app/uploads
      - ./.env:/app/.env
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
    restart: unless-stopped 